#!/usr/bin/env sh
# Generate a TypeScript module containing canonical userplugin sources.
set -eu

if [ "$#" -ne 2 ]; then
    printf 'usage: %s <source-userplugins-dir> <output-typescript-module>\n' "$0" >&2
    exit 2
fi

exec python3 - "$1" "$2" <<'PY'
import hashlib
import json
import os
import sys
from pathlib import Path

source = Path(sys.argv[1]).resolve()
output = Path(sys.argv[2]).resolve()

if not source.is_dir():
    raise SystemExit(f"userplugin source directory does not exist: {source}")

files: dict[str, str] = {}
for root, directories, names in os.walk(source, followlinks=False):
    directories.sort()
    names.sort()
    for name in (*directories, *names):
        path = Path(root, name)
        if path.is_symlink():
            raise SystemExit(f"userplugin source tree contains a symlink: {path}")
    for name in names:
        path = Path(root, name)
        relative = path.relative_to(source).as_posix()
        try:
            files[relative] = path.read_text(encoding="utf-8")
        except UnicodeDecodeError as exc:
            raise SystemExit(f"userplugin source is not UTF-8 text: {path}: {exc}") from exc

def digest_path(relative_root: str) -> str:
    root = source / relative_root
    digest = hashlib.sha256()
    if root.is_file():
        digest.update(b"file\0")
        digest.update(root.read_bytes())
        return digest.hexdigest()

    pending = [root]
    while pending:
        current = pending.pop()
        entries = sorted(current.iterdir(), key=lambda entry: entry.name)
        for entry in entries:
            relative = entry.relative_to(root).as_posix()
            if entry.is_symlink():
                raise SystemExit(f"userplugin source tree contains a symlink: {entry}")
            if entry.is_dir():
                digest.update(f"directory\0{relative}\0".encode())
                pending.append(entry)
            elif entry.is_file():
                digest.update(f"file\0{relative}\0".encode())
                digest.update(entry.read_bytes())
                digest.update(b"\0")
            else:
                raise SystemExit(f"userplugin source is not a regular file or directory: {entry}")
    return digest.hexdigest()

inventory = [
    {"destination": entry.name, "contentDigest": digest_path(entry.name)}
    for entry in sorted(source.iterdir(), key=lambda entry: entry.name)
    if entry.name != "_shared"
]

module = (
    "/* Generated by scripts/stage-userplugin-seeds.sh. Do not edit. */\n"
    f"export const embeddedUserPluginFiles = {json.dumps(files, ensure_ascii=False, separators=(',', ':'))} as const;\n"
    f"export const embeddedUserPluginInventory = {json.dumps(inventory, separators=(',', ':'))} as const;\n"
)
output.parent.mkdir(parents=True, exist_ok=True)
temporary = output.with_name(f".{output.name}.tmp")
temporary.write_text(module, encoding="utf-8")
temporary.replace(output)
PY
